.TH OGGSPLIT 1 "JAN 2010" Linux "User Manuals"
.SH NAME
oggSplit \- demultiplexes ogv files 
.SH SYNOPSIS
.B oggSplit file.ogv 
.SH DESCRIPTION
.B oggSplit
demultiplexes a multiplexed ogg file into several files with one stream each. 
 
An ogg video file (with extension .ogv) usually consist of an audio and a video stream. The command line tool oggSplit disjoins these streams into seperate files. This is also often called demultiplexing.

After that you have all embedded files of this input file with the following naming:

.I theora_<ID>.ogv:
This is the video stream encoded with the theora codec. The <ID> is the stream ID that is created by the encoder to uniquely identify this stream.

.I vorbis_<ID>.oga:
This is the audio stream encoded with the vorbis codec. The <ID> is the stream ID that is created by the encoder to uniquely identify this stream.

.I unknown_<ID>.ogv:
This is an unknown stream, that could not be interpreted. The <ID> is the stream ID that is created by the encoder to uniquely identify this stream.

All files are fully playable with your favoured video or audio player (except the streams, that are uninterpreted). 

.SH AUTHOR
Joern Seger <yorn at gmx dot net>

.SH "SEE ALSO"
.BR oggCut (1),
.BR oggCat (1),
.BR oggJoin (1),
.BR oggTranscode (1),
.BR oggSlideshow (1),
.BR oggThumb (1),
.BR oggSilence (1)
