language: c

os:
  - linux
  - osx

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get -qq update && sudo apt-get install -y check; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install check; fi

script:
  - cmake .
  - make
  - make test

compiler:
  - clang
  - gcc
